#pragma once
static const char WEB_PAGE[] PROGMEM = R"HTML(
<!doctype html><meta name=viewport content="width=device-width,initial-scale=1"><title>ESP32 Telemetry</title>
<style>body{font-family:system-ui;background:#101318;color:#eee;padding:14px;max-width:1000px;margin:auto}.g{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:8px}.c,.p{background:#181e25;border:1px solid #29323d;border-radius:10px;padding:10px}.k{font-size:11px;color:#98a7b6}.v{font-size:22px;font-weight:700}canvas{width:100%;height:180px;background:#0b0e12;border-radius:7px}pre{white-space:pre-wrap;word-break:break-all}</style>
<h2>ESP32 Telemetry</h2><div id=s>Waiting for frames…</div><div class=g id=g></div><div class=p><canvas id=c></canvas></div><div class=p><pre id=r></pre></div>
<script>
let H=[];const f=(v,d=1)=>v==null?'--':Number(v).toFixed(d);const card=(k,v,u='')=>`<div class=c><div class=k>${k}</div><div class=v>${v} ${u}</div></div>`;
function draw(){let c=document.getElementById('c'),x=c.getContext('2d'),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=c.clientHeight*devicePixelRatio;x.clearRect(0,0,w,h);if(H.length<2)return;let vals=[];H.forEach(p=>['temp','voltage','rpmScaled','pump'].forEach(k=>{if(Number.isFinite(p[k]))vals.push(p[k])}));if(!vals.length)return;let lo=Math.min(...vals),hi=Math.max(...vals);if(hi<=lo)hi=lo+1;let keys=['temp','voltage','rpmScaled','pump'],cols=['#67c8ff','#ffd166','#7fe29a','#d497ff'];keys.forEach((k,j)=>{x.strokeStyle=cols[j];x.lineWidth=2*devicePixelRatio;x.beginPath();let started=false;H.forEach((p,i)=>{let v=p[k];if(!Number.isFinite(v))return;let px=i/Math.max(1,H.length-1)*(w-8)+4,py=h-4-(v-lo)/(hi-lo)*(h-8);if(!started){x.moveTo(px,py);started=true}else x.lineTo(px,py)});x.stroke()})}
async function tick(){try{let s=await (await fetch('/api/state',{cache:'no-store'})).json();document.getElementById('s').textContent=`Frames ${s.validFrames} · rejected ${s.rejectedFrames} · state ${s.runState} · error ${s.errorCode}`;document.getElementById('g').innerHTML=card('Temperature',f(s.currentTemp),'°C')+card('Setpoint',f(s.desiredTemp),'°C')+card('Voltage',f(s.supply),'V')+card('RPM',s.fanRpm)+card('Pump',f(s.pump),'Hz');document.getElementById('r').textContent=s.raw||'';H.push({temp:s.currentTemp,voltage:s.supply,rpmScaled:(s.fanRpm||0)/100,pump:s.pump});if(H.length>360)H.shift();draw()}catch(e){document.getElementById('s').textContent='Offline'}}tick();setInterval(tick,5000);
</script>)HTML";
