#pragma once
static const char WEB_PAGE[] PROGMEM = R"HTML(
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Diesel Heater Lab</title>
<style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#0b0e12;color:#eef3f7;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif}.wrap{max-width:1100px;margin:auto;padding:14px}.top{display:flex;gap:10px;align-items:center;justify-content:space-between;position:sticky;top:0;background:#0b0e12e8;backdrop-filter:blur(8px);z-index:2;padding:8px 0}.title{font-weight:800;font-size:20px}.pill{padding:6px 10px;border:1px solid #33404c;border-radius:999px;font-size:12px;color:#b9c6d1}.ok{border-color:#275d47;color:#8be0b8}.bad{border-color:#743d3d;color:#ffaaaa}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.card,.panel{background:#141a21;border:1px solid #26313c;border-radius:13px;padding:11px}.k{font-size:11px;color:#91a1af;text-transform:uppercase;letter-spacing:.06em}.v{font-size:24px;font-weight:800;margin-top:3px}.u{font-size:12px;color:#8997a4;font-weight:600}.panel{margin-top:8px}.panel h3{font-size:13px;margin:0 0 8px;color:#bdc9d3}.chart{width:100%;height:180px;display:block;background:#0d1116;border-radius:9px}.legend{display:flex;flex-wrap:wrap;gap:10px;font-size:11px;color:#aebbc6;margin:7px 2px 0}.dot{width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:4px}.buttons{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}a.btn{display:inline-block;text-decoration:none;color:#eaf2f8;border:1px solid #364453;border-radius:9px;padding:9px 12px;font-size:13px}.raw{font:11px ui-monospace,SFMono-Regular,Consolas,monospace;word-break:break-all;color:#9aa9b6}.muted{color:#83919d;font-size:12px}.fault{margin-top:8px;padding:9px 11px;border-radius:10px;background:#2a1717;border:1px solid #603333;display:none}.fault.show{display:block}@media(min-width:700px){.grid{grid-template-columns:repeat(5,minmax(0,1fr))}.chart{height:210px}.title{font-size:23px}}
</style></head><body><div class="wrap">
<div class="top"><div><div class="title">🔥 Diesel Heater Lab</div><div class="muted">ESP32 passive monitor · factory controller remains in control</div></div><div id="link" class="pill">Waiting…</div></div>
<div id="fault" class="fault"></div>
<div class="grid" id="cards"></div>
<div class="panel"><h3>Temperatures</h3><canvas class="chart" id="tempChart"></canvas><div class="legend"><span><i class="dot" style="background:#67c8ff"></i>Room</span><span><i class="dot" style="background:#ffd166"></i>Setpoint</span><span><i class="dot" style="background:#ff8a6b"></i>Exchanger</span></div></div>
<div class="panel"><h3>Combustion / electrical</h3><canvas class="chart" id="powerChart"></canvas><div class="legend"><span><i class="dot" style="background:#7fe29a"></i>Supply V</span><span><i class="dot" style="background:#d497ff"></i>Glow A</span><span><i class="dot" style="background:#67c8ff"></i>Pump Hz</span></div></div>
<div class="panel"><h3>Fan</h3><canvas class="chart" id="fanChart"></canvas><div class="legend"><span><i class="dot" style="background:#ffd166"></i>RPM</span><span><i class="dot" style="background:#7fe29a"></i>Fan V</span></div></div>
<div class="panel"><h3>Raw bus data</h3><div id="status" class="muted"></div><p id="raw" class="raw">Waiting for a valid 48-byte frame…</p><div class="buttons"><a class="btn" href="/api/history.csv">Download CSV</a><a class="btn" href="/api/history" target="_blank">History JSON</a></div></div>
</div>
<script>
const $=id=>document.getElementById(id);let H=[];const MAX=360;
const n=(v,d=1)=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toFixed(d);
const card=(k,v,u='')=>`<div class="card"><div class="k">${k}</div><div class="v">${v}<span class="u"> ${u}</span></div></div>`;
function drawChart(id,series){const c=$(id),dpr=devicePixelRatio||1,w=c.clientWidth*dpr,h=c.clientHeight*dpr;if(c.width!==w||c.height!==h){c.width=w;c.height=h}const x=c.getContext('2d');x.clearRect(0,0,w,h);x.strokeStyle='#26313c';x.lineWidth=dpr;for(let i=1;i<4;i++){let y=i*h/4;x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke()}let vals=[];H.forEach(p=>series.forEach(s=>{let v=p[s.k];if(Number.isFinite(v))vals.push(v)}));if(vals.length<2)return;let lo=Math.min(...vals),hi=Math.max(...vals);if(hi-lo<.01){lo-=1;hi+=1}let pad=(hi-lo)*.08;lo-=pad;hi+=pad;series.forEach(s=>{x.strokeStyle=s.c;x.lineWidth=2*dpr;x.beginPath();let begun=false;H.forEach((p,i)=>{let v=p[s.k];if(!Number.isFinite(v))return;let px=(i/Math.max(1,H.length-1))*(w-8*dpr)+4*dpr;let py=h-4*dpr-(v-lo)/(hi-lo)*(h-8*dpr);if(!begun){x.moveTo(px,py);begun=true}else x.lineTo(px,py)});x.stroke()})}
function draw(){drawChart('tempChart',[{k:'room',c:'#67c8ff'},{k:'setpoint',c:'#ffd166'},{k:'exchanger',c:'#ff8a6b'}]);drawChart('powerChart',[{k:'supply',c:'#7fe29a'},{k:'glowA',c:'#d497ff'},{k:'pump',c:'#67c8ff'}]);drawChart('fanChart',[{k:'rpmK',c:'#ffd166'},{k:'fanV10',c:'#7fe29a'}])}
function addPoint(s){H.push({room:Number(s.currentTemp),setpoint:Number(s.desiredTemp),exchanger:Number(s.exchangerTemp),supply:Number(s.supply),glowA:Number(s.glowA),pump:Number(s.pump),rpmK:Number(s.fanRpm)/100,fanV10:Number(s.fanV)});if(H.length>MAX)H.shift()}
function render(s){$('link').textContent=s.valid&&s.ageMs<15000?'LIVE':'NO DATA';$('link').className='pill '+(s.valid&&s.ageMs<15000?'ok':'bad');$('cards').innerHTML=card('Room',n(s.currentTemp),'°C')+card('Setpoint',n(s.desiredTemp),'°C')+card('Exchanger',n(s.exchangerTemp,0),'°C')+card('Supply',n(s.supply),'V')+card('Fan',s.fanRpm||'—','rpm')+card('Pump',n(s.pump),'Hz')+card('Glow current',n(s.glowA,2),'A')+card('Glow voltage',n(s.glowV),'V')+card('Fan voltage',n(s.fanV),'V')+card('State',s.runStateName||'—');$('status').textContent=`Valid frames ${s.validFrames} · rejected ${s.rejectedFrames} · state ${s.runState} · error ${s.errorCode}`;$('raw').textContent=s.raw||'Waiting for a valid 48-byte frame…';let f=$('fault');if(Number(s.errorCode)>1){f.textContent=`⚠ Heater fault ${s.errorCode}: ${s.errorName}`;f.className='fault show'}else f.className='fault'}
async function loadHistory(){try{let a=await(await fetch('/api/history',{cache:'no-store'})).json();H=a.map(s=>({room:Number(s.room),setpoint:Number(s.setpoint),exchanger:Number(s.exchanger),supply:Number(s.supply),glowA:Number(s.glowA),pump:Number(s.pump),rpmK:Number(s.rpm)/100,fanV10:Number(s.glowV)})).slice(-MAX);draw()}catch(e){}}
async function tick(){try{let s=await(await fetch('/api/state',{cache:'no-store'})).json();render(s);addPoint(s);draw()}catch(e){$('link').textContent='OFFLINE';$('link').className='pill bad'}}
loadHistory().then(tick);setInterval(tick,5000);addEventListener('resize',draw);
</script></body></html>
)HTML";